### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by SeekPoint** [guotong1988/NL2SQL#2]
ub16hp@UB16HP:~/ub16_prj/NL2SQL$ python train.py 
Loading from original dataset
Loading data from data/train_tok.jsonl
Loading data from data/train_tok.tables.jsonl
Loading data from data/dev_tok.jsonl
Loading data from data/dev_tok.tables.jsonl
Loading data from data/test_tok.jsonl
Loading data from data/test_tok.tables.jsonl
Loading word embedding from glove/glove.42B.300d.txt
Using fixed embedding
Not using column attention on aggregator predicting
Not using column attention on selection predicting
Not using column attention on where predicting
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/aggregator_predict.py:55: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  att = self.softmax(att_val)
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/selection_predict.py:55: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  att = self.softmax(att_val)
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/sqlnet_condition_predict.py:123: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  num_col_att = self.softmax(num_col_att_val)
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/sqlnet_condition_predict.py:138: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  num_att = self.softmax(num_att_val)
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/sqlnet_condition_predict.py:163: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  col_att = self.softmax(col_att_val)
/home/ub16hp/ub16_prj/NL2SQL/sqlnet/model/modules/sqlnet_condition_predict.py:209: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  op_att = self.softmax(op_att_val)
Init dev acc_qm: 0.0
  breakdown on (agg, sel, where): [0.05498159 0.16363852 0.        ]
Epoch 1 @ 2018-10-01 12:27:07.696338
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    sql_data, table_data, TRAIN_ENTRY)
  File "/home/ub16hp/ub16_prj/NL2SQL/sqlnet/utils.py", line 145, in epoch_train
    cum_loss += loss.data.cpu().numpy()[0]*(ed - st)
IndexError: too many indices for array
ub16hp@UB16HP:~/ub16_prj/NL2SQL$

**Comment by SeekPoint** [comment]
should be pytorch0.3.0, not 0.4.0
